# Generated by Django 4.2.7 on 2024-06-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='sql_text',
            field=models.TextField(blank=True, verbose_name='Texto de SQLAlchemy'),
        ),
    ]
