# Generated by Django 4.2.7 on 2025-04-22 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reporte_descripcion_alter_reporte_sql_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_actualizacion', 'nombre'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AddField(
            model_name='reporte',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el reporte está disponible para su uso', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del reporte', verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se creó el reporte', verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del propósito y contenido del reporte', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre descriptivo para identificar el reporte', max_length=100, verbose_name='Nombre del Reporte'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='sql_text',
            field=models.TextField(blank=True, help_text='Consulta SQL utilizando la sintaxis de SQLAlchemy', verbose_name='Texto de SQLAlchemy'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['nombre'], name='home_report_nombre_7730de_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['fecha_creacion'], name='home_report_fecha_c_9d17f2_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['activo'], name='home_report_activo_2d5681_idx'),
        ),
    ]
