# Generated by Django 4.2.7 on 2024-06-19 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
        ('users', '0002_rename_usuario_registroauditoria_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroauditoria',
            old_name='user',
            new_name='usuario',
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedores', models.JSONField(default=list, verbose_name='Proveedores')),
                ('macrozonas', models.JSONField(default=list, verbose_name='Macrozonas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisos.confempresas', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuario',
            },
        ),
    ]
