# Generated by Django 4.2.7 on 2024-06-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_registroauditoria_usuario_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='macrozonas',
            field=models.JSONField(blank=True, default=list, verbose_name='Macrozonas'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='proveedores',
            field=models.JSONField(blank=True, default=list, verbose_name='Proveedores'),
        ),
    ]
