# Generated by Django 4.2.7 on 2024-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpermission_macrozonas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='macrozonas',
            field=models.TextField(blank=True, verbose_name='Macrozonas'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='proveedores',
            field=models.TextField(blank=True, verbose_name='Proveedores'),
        ),
    ]
