# Generated by Django 4.2.7 on 2025-04-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userpermission_macrozonas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP de inicio de sesión'),
        ),
        migrations.AddField(
            model_name='user',
            name='session_security',
            field=models.JSONField(blank=True, default=dict, help_text='Datos de seguridad de sesión como dispositivos conocidos', verbose_name='Seguridad de sesión'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Clave secreta para la autenticación de dos factores', max_length=255, null=True, verbose_name='TOTP Secret'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Indica si la autenticación de dos factores está habilitada', verbose_name='2FA Habilitado'),
        ),
    ]
