# Generated by Django 4.2.7 on 2024-06-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivosTsol',
        ),
        migrations.DeleteModel(
            name='MapeoCaracteres',
        ),
    ]
