# Generated by Django 4.2.7 on 2025-05-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargues', '0002_delete_archivostsol_delete_mapeocaracteres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infoventas',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('cod_cliente', models.CharField(db_column='Cod. cliente', max_length=30)),
                ('nom_cliente', models.TextField(db_column='Nom. Cliente')),
                ('cod_vendedor', models.CharField(db_column='Cod. vendedor', max_length=30)),
                ('nombre', models.TextField(db_column='Nombre')),
                ('cod_productto', models.CharField(db_column='Cod. productto', max_length=30)),
                ('descripcion', models.TextField(db_column='Descripción')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('fac_numero', models.CharField(db_column='Fac. numero', max_length=30)),
                ('cantidad', models.FloatField(db_column='Cantidad')),
                ('vta_neta', models.FloatField(db_column='Vta neta')),
                ('tipo', models.CharField(db_column='Tipo', max_length=30)),
                ('costo', models.FloatField(db_column='Costo')),
                ('unidad', models.CharField(blank=True, db_column='Unidad', max_length=30, null=True)),
                ('pedido', models.CharField(blank=True, db_column='Pedido', max_length=30, null=True)),
                ('proveedor', models.TextField(blank=True, db_column='Proveedor', null=True)),
                ('empresa', models.CharField(blank=True, db_column='Empresa', max_length=100, null=True)),
                ('lider', models.TextField(blank=True, db_column='Líder', null=True)),
                ('area', models.TextField(blank=True, db_column='Área', null=True)),
                ('codigo_bodega', models.CharField(blank=True, db_column='Codigo bodega', max_length=30, null=True)),
                ('bodega', models.CharField(blank=True, db_column='Bodega', max_length=100, null=True)),
                ('categoria', models.TextField(blank=True, db_column='Categoría', null=True)),
                ('tipo_prod', models.TextField(blank=True, db_column='Tipo Prod', null=True)),
                ('cod_barra', models.CharField(blank=True, db_column='Cod. Barra', max_length=50, null=True)),
                ('nbLinea', models.FloatField(blank=True, db_column='nbLinea', null=True)),
            ],
            options={
                'db_table': 'infoventas',
                'managed': False,
            },
        ),
    ]
