# Generated by Django 4.2.7 on 2025-10-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargues", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsiVamos",
            fields=[
                (
                    "asesor",
                    models.CharField(
                        db_column="asesor",
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("para", models.TextField(blank=True, db_column="para", null=True)),
                ("copia", models.TextField(blank=True, db_column="copia", null=True)),
                (
                    "campo_30",
                    models.CharField(
                        blank=True, db_column="campo_30", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dim_asi_vamos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "cod_cliente",
                    models.CharField(
                        db_column="cod_cliente",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom_cliente",
                    models.TextField(blank=True, db_column="nom_cliente", null=True),
                ),
                (
                    "empresas",
                    models.CharField(
                        blank=True, db_column="empresas", max_length=100, null=True
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(blank=True, db_column="fecha_ingreso", null=True),
                ),
                (
                    "nit",
                    models.CharField(
                        blank=True, db_column="nit", max_length=50, null=True
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, db_column="direccion", null=True),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, db_column="telefono", max_length=50, null=True
                    ),
                ),
                (
                    "representante_legal",
                    models.CharField(
                        blank=True,
                        db_column="representante_legal",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "codigo_municipio",
                    models.CharField(
                        blank=True,
                        db_column="codigo_municipio",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "codigo_negocio",
                    models.CharField(
                        blank=True, db_column="codigo_negocio", max_length=20, null=True
                    ),
                ),
                (
                    "tipo_negocio",
                    models.CharField(
                        blank=True, db_column="tipo_negocio", max_length=50, null=True
                    ),
                ),
                (
                    "estracto",
                    models.CharField(
                        blank=True, db_column="estracto", max_length=10, null=True
                    ),
                ),
                (
                    "barrio",
                    models.CharField(
                        blank=True, db_column="barrio", max_length=100, null=True
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        blank=True, db_column="clasificacion", max_length=100, null=True
                    ),
                ),
                (
                    "comuna",
                    models.CharField(
                        blank=True, db_column="comuna", max_length=50, null=True
                    ),
                ),
                (
                    "estrato",
                    models.CharField(
                        blank=True, db_column="estrato", max_length=10, null=True
                    ),
                ),
                (
                    "coord",
                    models.CharField(
                        blank=True, db_column="coord", max_length=100, null=True
                    ),
                ),
                (
                    "longitud",
                    models.FloatField(blank=True, db_column="longitud", null=True),
                ),
                (
                    "latitud",
                    models.FloatField(blank=True, db_column="latitud", null=True),
                ),
            ],
            options={
                "db_table": "dim_clientes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CuotasVendedores",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "cod_ejecutivo",
                    models.CharField(db_column="cod_ejecutivo", max_length=30),
                ),
                ("periodo", models.CharField(db_column="periodo", max_length=20)),
                ("anio", models.IntegerField(db_column="anio")),
                ("mes", models.IntegerField(db_column="mes")),
                ("mes_nombre", models.CharField(db_column="mes_nombre", max_length=15)),
                ("cuota", models.FloatField(blank=True, db_column="cuota", null=True)),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, db_column="fecha_actualizacion"
                    ),
                ),
            ],
            options={
                "db_table": "fact_cuotas_vendedores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Estructura",
            fields=[
                (
                    "cod_ejecutivo",
                    models.CharField(
                        db_column="cod_ejecutivo",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom_ejecutivo",
                    models.CharField(
                        blank=True, db_column="nom_ejecutivo", max_length=200, null=True
                    ),
                ),
                (
                    "lider_tsol",
                    models.CharField(
                        blank=True, db_column="lider_tsol", max_length=200, null=True
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True, db_column="empresa", max_length=100, null=True
                    ),
                ),
                (
                    "lider_comercial",
                    models.CharField(
                        blank=True,
                        db_column="lider_comercial",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "cod_bod",
                    models.CharField(
                        blank=True, db_column="cod_bod", max_length=20, null=True
                    ),
                ),
                (
                    "bodega",
                    models.CharField(
                        blank=True, db_column="bodega", max_length=100, null=True
                    ),
                ),
                (
                    "area_nombre",
                    models.CharField(
                        blank=True, db_column="area_nombre", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dim_estructura",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "codigo_sap",
                    models.CharField(
                        db_column="codigo_sap",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.TextField(blank=True, db_column="nombre", null=True)),
                (
                    "tipo_referencia",
                    models.CharField(
                        blank=True,
                        db_column="tipo_referencia",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        blank=True, db_column="unidad", max_length=20, null=True
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(
                        blank=True, db_column="codigo_barras", max_length=50, null=True
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        blank=True, db_column="proveedor", max_length=100, null=True
                    ),
                ),
                (
                    "proveedor_2",
                    models.CharField(
                        blank=True, db_column="proveedor_2", max_length=100, null=True
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, db_column="categoria", max_length=100, null=True
                    ),
                ),
                (
                    "tipo_prod",
                    models.CharField(
                        blank=True, db_column="tipo_prod", max_length=100, null=True
                    ),
                ),
                (
                    "contenido",
                    models.CharField(
                        blank=True, db_column="contenido", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dim_productos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductosColgate",
            fields=[
                (
                    "cod_texto",
                    models.CharField(
                        db_column="cod_texto",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pro_cod",
                    models.CharField(
                        blank=True, db_column="pro_cod", max_length=50, null=True
                    ),
                ),
                (
                    "producto",
                    models.TextField(blank=True, db_column="producto", null=True),
                ),
                (
                    "alterno",
                    models.CharField(
                        blank=True, db_column="alterno", max_length=50, null=True
                    ),
                ),
                (
                    "cod",
                    models.CharField(
                        blank=True, db_column="cod", max_length=50, null=True
                    ),
                ),
                (
                    "portafolio",
                    models.IntegerField(blank=True, db_column="portafolio", null=True),
                ),
                (
                    "inici",
                    models.IntegerField(blank=True, db_column="inici", null=True),
                ),
                (
                    "subc",
                    models.CharField(
                        blank=True, db_column="subc", max_length=100, null=True
                    ),
                ),
                (
                    "producto_alt",
                    models.TextField(blank=True, db_column="producto_alt", null=True),
                ),
            ],
            options={
                "db_table": "dim_productos_colgate",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Proveedores",
            fields=[
                (
                    "codigo_proveedor",
                    models.CharField(
                        db_column="codigo_proveedor",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("emails", models.TextField(blank=True, db_column="emails", null=True)),
                ("copia", models.TextField(blank=True, db_column="copia", null=True)),
                (
                    "columnas",
                    models.IntegerField(blank=True, db_column="columnas", null=True),
                ),
                (
                    "periodo",
                    models.FloatField(blank=True, db_column="periodo", null=True),
                ),
                (
                    "ppks",
                    models.CharField(
                        blank=True, db_column="ppks", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dim_proveedores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rutero",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        db_column="codigo",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cod_asesor",
                    models.CharField(
                        blank=True, db_column="cod_asesor", max_length=30, null=True
                    ),
                ),
                (
                    "asesores",
                    models.CharField(
                        blank=True, db_column="asesores", max_length=200, null=True
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True, db_column="documento", max_length=50, null=True
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        blank=True, db_column="cliente", max_length=200, null=True
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True, db_column="razon_social", max_length=200, null=True
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, db_column="direccion", null=True),
                ),
                (
                    "barrio",
                    models.CharField(
                        blank=True, db_column="barrio", max_length=100, null=True
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True, db_column="ciudad", max_length=100, null=True
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, db_column="telefono", max_length=50, null=True
                    ),
                ),
                (
                    "sucursal",
                    models.CharField(
                        blank=True, db_column="sucursal", max_length=20, null=True
                    ),
                ),
                (
                    "dias",
                    models.CharField(
                        blank=True, db_column="dias", max_length=20, null=True
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(blank=True, db_column="orden", null=True),
                ),
                (
                    "orden_dia",
                    models.IntegerField(blank=True, db_column="orden_dia", null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=200, null=True
                    ),
                ),
                (
                    "segmento",
                    models.CharField(
                        blank=True, db_column="segmento", max_length=100, null=True
                    ),
                ),
                (
                    "telefono2",
                    models.CharField(
                        blank=True, db_column="telefono2", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dim_rutero",
                "managed": False,
            },
        ),
    ]
