# Generated by Django 4.2.7 on 2024-06-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_alter_permisosbarra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisosbarra',
            options={'managed': False, 'permissions': (('nav_bar', 'Ver la barra de menú'), ('cubo', 'Generar cubo de ventas'), ('proveedor', 'Generar cubo de ventas para proveedor'), ('interface', 'Generar interface contable'), ('cargue_plano', 'cargar archivo plano'), ('cargue_tsol', 'Cargue archivo plano tsol'), ('plano', 'Generar archivo plano'), ('informe_bi', 'Informe Bi'), ('actualizar_base', 'Actualzación de datos'), ('actualizacion_bi', 'Actualizar Bi'), ('admin', 'Ir al Administrador'))},
        ),
    ]
