# Generated by Django 4.2.7 on 2025-04-22 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_alter_permisosbarra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confdt',
            options={'ordering': ['nbDt'], 'verbose_name': 'Configuración Rango de Fecha', 'verbose_name_plural': 'Configuración Rangos de Fechas'},
        ),
        migrations.AlterModelOptions(
            name='confempresas',
            options={'ordering': ['id', 'nmEmpresa'], 'verbose_name': 'Configuración Empresa', 'verbose_name_plural': 'Configuración Empresas'},
        ),
        migrations.AlterModelOptions(
            name='confserver',
            options={'ordering': ['nbServer'], 'verbose_name': 'Configuración Servidor', 'verbose_name_plural': 'Configuración Servidores'},
        ),
        migrations.AlterModelOptions(
            name='confsql',
            options={'ordering': ['nbSql'], 'verbose_name': 'Configuración Proceso SQL', 'verbose_name_plural': 'Configuración Procesos SQL'},
        ),
        migrations.AlterModelOptions(
            name='conftipo',
            options={'ordering': ['nbTipo'], 'verbose_name': 'Configuración Tipo Servidor', 'verbose_name_plural': 'Configuración Tipos de Servidores'},
        ),
        migrations.AlterModelOptions(
            name='permisosbarra',
            options={'managed': False, 'permissions': (('nav_bar', 'Ver la barra de menú'), ('panel_cubo', 'Panel de cubo'), ('panel_bi', 'Panel de BI'), ('panel_actualizacion', 'Panel de Actualización de datos'), ('panel_interface', 'Panel de Interfaces Contables'), ('cubo', 'Generar cubo de ventas'), ('proveedor', 'Generar cubo de ventas para proveedor'), ('interface', 'Generar interface contable'), ('plano', 'Generar archivo plano'), ('cargue_plano', 'Cargar archivo plano'), ('cargue_tsol', 'Cargue archivo plano TSOL'), ('informe_bi', 'Informe BI'), ('actualizar_base', 'Actualización de datos'), ('actualizacion_bi', 'Actualizar BI'), ('admin', 'Ir al Administrador')), 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AddField(
            model_name='confempresas',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='confserver',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='confsql',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', null=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='confsql',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='conftipo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', null=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='conftipo',
            name='txDescripcion',
            field=models.CharField(blank=True, help_text='Descripción del tipo de servidor', max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='confdt',
            name='nbDt',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, 'El ID debe ser un número positivo')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='confdt',
            name='nmDt',
            field=models.CharField(blank=True, help_text='Nombre descriptivo para identificar el rango de fechas', max_length=100, null=True, verbose_name='Nombre Rango de Fecha'),
        ),
        migrations.AlterField(
            model_name='confdt',
            name='txDtFin',
            field=models.TextField(blank=True, help_text='Fecha de fin del periodo', null=True, verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='confdt',
            name='txDtIni',
            field=models.TextField(blank=True, help_text='Fecha de inicio del periodo', null=True, verbose_name='Fecha Inicial'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='dataset_id_powerbi',
            field=models.CharField(blank=True, help_text='Identificador del conjunto de datos en PowerBI', max_length=255, null=True, verbose_name='Dataset PowerBI'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='dbBi',
            field=models.CharField(blank=True, help_text='Nombre de la base de datos de Business Intelligence', max_length=150, null=True, verbose_name='Base de datos BI'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='dbSidis',
            field=models.CharField(blank=True, help_text='Nombre de la base de datos Sidis', max_length=150, null=True, verbose_name='Base de datos Sidis'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='estado',
            field=models.IntegerField(blank=True, help_text='Estado de la empresa (1: activo, 0: inactivo)', null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, 'El ID debe ser un número positivo')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre de la base de datos', max_length=100, null=True, verbose_name='Nombre de la Base'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nbServerBi',
            field=models.BigIntegerField(blank=True, help_text='ID del servidor donde se aloja PowerBI', null=True, verbose_name='ID Servidor PowerBI'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nbServerSidis',
            field=models.BigIntegerField(blank=True, help_text='ID del servidor donde se aloja Sidis', null=True, verbose_name='ID Servidor Sidis'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmEmpresa',
            field=models.CharField(blank=True, help_text='Nombre completo de la empresa', max_length=100, null=True, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureCsv',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento para exportar a CSV', max_length=30, null=True, verbose_name='Procedimiento a CSV'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureCsv2',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento alternativo para CSV', max_length=30, null=True, verbose_name='Procedimiento a CSV2'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureExcel',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento para exportar a Excel', max_length=30, null=True, verbose_name='Procedimiento a Excel'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureExcel2',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento alternativo para Excel', max_length=30, null=True, verbose_name='Procedimiento a Excel2'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureInterface',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento para la interfaz', max_length=30, null=True, verbose_name='Procedimiento Interface'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='nmProcedureSql',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento para exportar SQL', max_length=30, null=True, verbose_name='Procedimiento a SQL'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='report_id_powerbi',
            field=models.CharField(blank=True, help_text='Identificador del reporte en PowerBI', max_length=255, null=True, verbose_name='ID Reporte PowerBI'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureCargue',
            field=models.TextField(blank=True, help_text='Procedimiento SQL para carga de datos', null=True, verbose_name='Procesos SQL del Cargue'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureCsv',
            field=models.TextField(blank=True, help_text='SQL para exportación a CSV', null=True, verbose_name='Procesos SQL a CSV'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureCsv2',
            field=models.TextField(blank=True, help_text='SQL alternativo para exportación a CSV', null=True, verbose_name='Procesos SQL a CSV2'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureExcel',
            field=models.TextField(blank=True, help_text='SQL para exportación a Excel', null=True, verbose_name='Procesos SQL a Excel'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureExcel2',
            field=models.TextField(blank=True, help_text='SQL alternativo para exportación a Excel', null=True, verbose_name='Procesos SQL a Excel2'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureExtrae',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento para extracción de datos', max_length=100, null=True, verbose_name='Procesos SQL Extractor'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureInterface',
            field=models.TextField(blank=True, help_text='SQL para el procesamiento de interfaz', null=True, verbose_name='Procesos SQL de Interface'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='txProcedureSql',
            field=models.TextField(blank=True, help_text='SQL para exportación SQL', null=True, verbose_name='Procesos SQL a SQL'),
        ),
        migrations.AlterField(
            model_name='confempresas',
            name='url_powerbi',
            field=models.TextField(blank=True, help_text='URL para acceder al reporte público en PowerBI', null=True, verbose_name='URL Pública PowerBI'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='hostServer',
            field=models.CharField(blank=True, help_text='Dirección IP o hostname del servidor', max_length=100, null=True, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='nbServer',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, 'El ID debe ser un número positivo')], verbose_name='ID del Servidor'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='nbTipo',
            field=models.BigIntegerField(blank=True, help_text='Tipo de servidor según la tabla de configuración de tipos', null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='nmServer',
            field=models.CharField(blank=True, help_text='Nombre descriptivo del servidor', max_length=30, null=True, verbose_name='Descripción del Servidor'),
        ),
        migrations.AlterField(
            model_name='confserver',
            name='portServer',
            field=models.CharField(blank=True, help_text='Puerto para la conexión al servidor', max_length=10, null=True, verbose_name='Puerto'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='nbSql',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, 'El ID debe ser un número positivo')], verbose_name='ID del Proceso'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='nmProcedure_in',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento almacenado para carga', max_length=100, null=True, verbose_name='Nombre del Procedimiento Carga'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='nmProcedure_out',
            field=models.CharField(blank=True, help_text='Nombre del procedimiento almacenado para extracción', max_length=100, null=True, verbose_name='Nombre del Procedimiento Extractor'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='nmReporte',
            field=models.CharField(blank=True, help_text='Nombre descriptivo del proceso SQL', max_length=100, null=True, verbose_name='Nombre del Proceso'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='txDescripcion',
            field=models.CharField(blank=True, help_text='Descripción detallada del propósito del proceso SQL', max_length=255, null=True, verbose_name='Descripción del Proceso'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='txSql',
            field=models.TextField(blank=True, help_text='Consulta SQL a ejecutar', null=True, verbose_name='SQL Script'),
        ),
        migrations.AlterField(
            model_name='confsql',
            name='txTabla',
            field=models.CharField(blank=True, help_text='Tabla donde se insertarán los resultados', max_length=100, null=True, verbose_name='Tabla de Inserción'),
        ),
        migrations.AlterField(
            model_name='conftipo',
            name='nbTipo',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, 'El ID debe ser un número positivo')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conftipo',
            name='nmUsr',
            field=models.CharField(blank=True, help_text='Nombre de usuario para la conexión', max_length=50, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='conftipo',
            name='txPass',
            field=models.TextField(blank=True, help_text='Contraseña para la conexión', null=True, verbose_name='Password'),
        ),
        migrations.AddIndex(
            model_name='confempresas',
            index=models.Index(fields=['name'], name='empresa_name_idx'),
        ),
        migrations.AddIndex(
            model_name='confempresas',
            index=models.Index(fields=['nmEmpresa'], name='empresa_nmempresa_idx'),
        ),
        migrations.AddIndex(
            model_name='confserver',
            index=models.Index(fields=['hostServer'], name='server_host_idx'),
        ),
        migrations.AddIndex(
            model_name='confsql',
            index=models.Index(fields=['nmReporte'], name='sql_nmreporte_idx'),
        ),
        migrations.AddIndex(
            model_name='confsql',
            index=models.Index(fields=['txDescripcion'], name='sql_descripcion_idx'),
        ),
    ]
