# Generated by Django 4.2.7 on 2025-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0004_alter_confdt_options_alter_confempresas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amovildesk', models.BooleanField(default=False, verbose_name='Puede generar reporte Amovildesk')),
            ],
            options={
                'permissions': [('cubo', 'Puede ver Cubo de Ventas'), ('proveedor', 'Puede ver Informe de Proveedores'), ('amovildesk', 'Puede ver Informe Amovildesk')],
            },
        ),
    ]
