# Generated by Django 4.2.7 on 2025-05-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_permiso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.AlterModelOptions(
            name='permisosbarra',
            options={'managed': False, 'permissions': (('nav_bar', 'Ver la barra de menú'), ('panel_cubo', 'Panel de cubo'), ('panel_bi', 'Panel de BI'), ('panel_actualizacion', 'Panel de Actualización de datos'), ('panel_interface', 'Panel de Interfaces Contables'), ('cubo', 'Generar cubo de ventas'), ('proveedor', 'Generar cubo de ventas para proveedor'), ('interface', 'Generar interface contable'), ('plano', 'Generar archivo plano'), ('cargue_plano', 'Cargar archivo plano'), ('cargue_tsol', 'Cargue archivo plano TSOL'), ('informe_bi', 'Informe BI'), ('actualizar_base', 'Actualización de datos'), ('actualizacion_bi', 'Actualizar BI'), ('admin', 'Ir al Administrador'), ('amovildesk', 'Puede ver Informe Amovildesk')), 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
    ]
